spring:
  config:
    import:
  profiles:
    group:
      main:
      local:
      - data-local
      - web-local
      prod:
      release:
      performance:
    default: local

chatgpt:
  api-key: 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